config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from config.ddtb import DEBUG_TOOLBAR_PATH

from freelance.views import RegisterView


urlpatterns = [
    path('', include('freelance.urls')),
    path('ratings/', include('ratings.urls')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    DEBUG_TOOLBAR_PATH, 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

freelance/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from config.ddtb import DEBUG_TOOLBAR_PATH
from freelance.views import RegisterView


urlpatterns = [
    path('', include('freelance.urls')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    DEBUG_TOOLBAR_PATH, 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

freelance/freelance/urls.py
from django.urls import path
from .views import (
    CustomLogoutView,
    MainPageView,
    ServiceListView,
    ServiceDetailView,
    OrderListView,
    OrderDetailView,
    OrderCreateView,
    OrderEditView,
    ExecutorListView,
    ExecutorDetailView,
    CustomerListView,
    CustomerDetailView,
    ExecutorsRequestsListView,
)

app_name = "freelance"

urlpatterns = [
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path("", MainPageView.as_view(), name="main_page"),
    
    path("executors/", ExecutorListView.as_view(), name="executor-list"),
    path("executors/<int:pk>/", ExecutorDetailView.as_view(), name="executor-detail"),
    path("executors/requests/", ExecutorsRequestsListView.as_view(), name="executor-requests"),

    path("customers/", CustomerListView.as_view(), name="customer-list"),
    path("customers/<int:pk>/", CustomerDetailView.as_view(), name="customer-detail"),

    path("services/", ServiceListView.as_view(), name="service-list"),
    path("services/<int:pk>/", ServiceDetailView.as_view(), name="service-detail"),
    # Orders
    path("orders/create/", OrderCreateView.as_view(), name="order-create"),
    path("orders/edit/<int:pk>", OrderEditView.as_view(), name="order-edit"),
    path("orders/", OrderListView.as_view(), name="order-list"),
    path("orders/<int:pk>/", OrderDetailView.as_view(), name="order-detail"),
    path("orders/success/", OrderListView.as_view() , name="order-success"),
    
]

freelance/urls.py
from django.urls import path
from .views import (
    CustomLogoutView,
    MainPageView,
    ServiceListView,
    ServiceDetailView,
    OrderListView,
    OrderDetailView,
    OrderCreateView,
    OrderEditView,
    OrderRequestView,
    ExecutorListView,
    ExecutorDetailView,
    ExecutorsRequestsListView,
    CustomerListView,
    CustomerDetailView,
    CustomerAccessOrderView,
    CustomerAccessOrdersView,
)

app_name = "freelance"

urlpatterns = [
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path("", MainPageView.as_view(), name="main_page"),
    # Executors
    path("executors/", ExecutorListView.as_view(), name="executor-list"),
    path("executors/<int:pk>/", ExecutorDetailView.as_view(), name="executor-detail"),
    path("executors/requests/", ExecutorsRequestsListView.as_view(), name="executor-requests"),
    # Customers
    path("customers/", CustomerListView.as_view(), name="customer-list"),
    path("customers/<int:pk>/", CustomerDetailView.as_view(), name="customer-detail"),
    path("customers/access-orders/", CustomerAccessOrdersView.as_view(), name="customer-access-orders"),
    path("customers/access-order/<int:pk>/", CustomerAccessOrderView.as_view(), name="customer-access-order"),

    path("services/", ServiceListView.as_view(), name="service-list"),
    path("services/<int:pk>/", ServiceDetailView.as_view(), name="service-detail"),
    # Orders
    path("orders/create/", OrderCreateView.as_view(), name="order-create"),
    path("orders/edit/<int:pk>", OrderEditView.as_view(), name="order-edit"),
    path("orders/", OrderListView.as_view(), name="order-list"),
    path("orders/<int:pk>", OrderDetailView.as_view(), name="order-detail"),
    path("orders/request/<int:pk>", OrderRequestView.as_view(), name="order-request"),
    path("orders/success/", OrderListView.as_view() , name="order-success"),
]

ratings/urls.py
from django.urls import path

from ratings.views import RatingListView, RatingUpdateView

app_name = "ratings"

urlpatterns = [
    path("all", RatingListView.as_view(), name="rating_list"),
    path("update/<int:order>/", RatingUpdateView.as_view(), name="rating_update"),
]

freelance/freelance/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import validate_slug


class UserProfile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        verbose_name="Пользователь",
        validators=[validate_slug],
    )
    phone = models.CharField(
        max_length=12, blank=True, null=True, verbose_name="Телефон"
    )
    rating = models.FloatField(default=0.0, verbose_name="Рейтинг")

    def __str__(self):
        phone_display = self.phone if self.phone else "Нет телефона"
        return f"{self.user.username} - {phone_display}"


class Executor(models.Model):
    profile = models.OneToOneField(
        UserProfile,
        on_delete=models.CASCADE,
        verbose_name="Профиль",
    )
    skills = models.TextField(blank=True, verbose_name="Навыки")
    avatar = models.ImageField(
        upload_to="user_avatars", null=True, blank=True, verbose_name="Аватар"
    )

    def __str__(self):
        return (
            super().__str__()
            + f" - Навыки: {self.skills if self.skills else 'Не указаны'}"
        )

    class Meta:
        verbose_name = "Исполнитель"
        verbose_name_plural = "Исполнители"


class Customer(models.Model):
    profile = models.OneToOneField(
        UserProfile,
        on_delete=models.CASCADE,
        verbose_name="Профиль",
    )
    preferences = models.TextField(blank=True, verbose_name="Предпочтения")

    def __str__(self):
        return (
            f"{self.profile.user.username} - email: {self.profile.user.email if self.profile.user.email else 'Не указаны'}"
        )

    class Meta:
        verbose_name = "Заказчик"
        verbose_name_plural = "Заказчики"


class Service(models.Model):
    class ServicesType(models.TextChoices):
        DESIGN = "design", "Дизайн"
        DEVELOPMENT = "development", "Разработка"
        SUPPORT = "support", "Поддержка"

    executor = models.ForeignKey(
        Executor, on_delete=models.CASCADE, verbose_name="Исполнитель"
    )
    name = models.CharField(
        max_length=255, blank=True, null=True, verbose_name="Название"
    )
    description = models.TextField(verbose_name="Описание")
    service_type = models.CharField(
        max_length=11,
        choices=ServicesType.choices,
        default="design",
        verbose_name="Тип услуги",
    )
    price = models.DecimalField(
        verbose_name="Стоимость", max_digits=10, decimal_places=2, default=0
    )

    def __str__(self):
        return self.name or "Неименованная услуга"

    class Meta:
        verbose_name = "Услуга"
        verbose_name_plural = "Услуги"


class Order(models.Model):
    # service = models.OneToOneField(
    #     Service, on_delete=models.CASCADE, primary_key=True, verbose_name="Услуга"
    # )
    order_type = models.CharField(
        max_length=11,
        choices=Service.ServicesType.choices,
        default="design",
        verbose_name="Тип заказа",
    )

    title = models.CharField(max_length=255, verbose_name="Заголовок")
    description = models.TextField(verbose_name="Описание")
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Создан", null=True
    )
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Обновлен", null=True)
    price = models.DecimalField(
        verbose_name="Стоимость", max_digits=10, decimal_places=2, default=0
    )

    customer = models.ForeignKey(
        Customer,
        on_delete=models.CASCADE,
        related_name="customers",
        blank=True,
        null=True,
        verbose_name="Заказчик",
    )

    executor = models.ForeignKey(
        Executor,
        on_delete=models.CASCADE,
        related_name="executors",
        blank=True,
        null=True,
        verbose_name="Исполнитель",
    )

    order_taken = models.BooleanField(default=False, verbose_name="Заказ сделан")
    order_taken_at = models.DateTimeField(
        null=True, blank=True, verbose_name="Время принятия заказа"
    )


    def __str__(self):
        return self.title or self.description or "Неизвестный заказ"

    class Meta:
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"


class Tag(models.Model):
    name = models.CharField(max_length=100, verbose_name="Имя тега")
    service = models.ForeignKey(
        Service,
        on_delete=models.CASCADE,
        related_name="tags",
        blank=True,
        null=True,
        verbose_name="Услуга",
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Тег"
        verbose_name_plural = "Теги"


class OrderRequest(models.Model):
    order = models.ForeignKey(
        Order, on_delete=models.CASCADE, related_name="requests", verbose_name="Заказ"
    )
    executor = models.ForeignKey(
        Executor,
        on_delete=models.CASCADE,
        related_name="order_requests",
        verbose_name="Исполнитель",
        default=None,
        null=True,
    )
    about_executor = models.TextField(verbose_name="Об исполнителе", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    status = models.CharField(
        max_length=20,
        choices=[
            ("pending", "В ожидании"),
            ("accepted", "Принято"),
            ("rejected", "Отклонено"),
        ],
        default="pending",
        verbose_name="Статус",
    )

    class Meta:
        unique_together = ("order", "executor")
        verbose_name = "Заявка на заказ"
        verbose_name_plural = "Заявки на заказы"

    def __str__(self):
        return f"{self.order.title} - {self.executor.profile.user.username}"

Lesson-1 (extract.me)/Lesson-1/freelance/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ["order_type", "title", "description", "price"]

Lesson-1 (extract.me)/Lesson-1/freelance/views.py
from django.views.generic import (ListView, DetailView, TemplateView, CreateView, UpdateView,)
from .models import Service, Order, Executor, Customer
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy

from freelance.forms import OrderForm
from .models import Service, Order, Executor, Customer



class CustomerLogoutView(LogoutView):
    next_page = reverse_lazy("login") #Перенаправление на нужную страницу.


class MainPageView(TemplateView):
    template_name = "basic/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["message"] = "Это главная страница проекта"
        return context


class ExecutorListView(ListView):
    model = Executor
    template_name = (
        "freelance/executors/executor_list.html"  # Укажите ваш путь к шаблону
    )
    context_object_name = "executors"


class ExecutorDetailView(DetailView):
    model = Executor
    template_name = (
        "freelance/executors/executor_detail.html"  # Укажите ваш путь к шаблону
    )
    context_object_name = "executor"


class CustomerListView(ListView):
    model = Customer
    template_name = (
        "freelance/customers/customer_list.html"  # Укажите ваш путь к шаблону
    )
    context_object_name = "customers"


class CustomerDetailView(DetailView):
    model = Customer
    template_name = (
        "freelance/customers/customer_detail.html"  # Укажите ваш путь к шаблону
    )
    context_object_name = "customer"


class ServiceListView(ListView):
    model = Service
    template_name = "freelance/services/service_list.html"  # Укажите ваш путь к шаблону
    context_object_name = "services"


class ServiceDetailView(DetailView):
    model = Service
    template_name = (
        "freelance/services/service_detail.html"  # Укажите ваш путь к шаблону
    )
    context_object_name = "service"


class OrderListView(ListView):
    model = Order
    template_name = "freelance/orders/order_list.html"  # Укажите ваш путь к шаблону
    context_object_name = "orders"


class OrderDetailView(DetailView):
    model = Order
    template_name = "freelance/orders/order_detail.html"  # Укажите ваш путь к шаблону
    context_object_name = "order"


class CustomLogoutView(LogoutView):
    next_page = reverse_lazy("login")  # Перенаправление на главную страницу


class OrderCreateView(LoginRequiredMixin, CreateView):
    template_name = "freelance/orders/order_create.html"
    form_class = OrderForm
    success_url = reverse_lazy(
        "freelance:order-success"
    )  # URL для перенаправления после успешного создания

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title_label"] = "Создание заказа"
        return context

    def form_valid(self, form):
        # Получаем объект Customer для текущего пользователя
        customer_profile, created = Customer.objects.get_or_create(
            user=self.request.user
        )
        form.instance.customer = customer_profile
        return super().form_valid(form)


class OrderEditView(LoginRequiredMixin, UpdateView):
    template_name = "freelance/orders/order_create.html"
    form_class = OrderForm
    model = Order
    success_url = reverse_lazy(
        "freelance:order-success"
    )  # URL для перенаправления после успешного создания

    def get_context_data(self, **kwargs):
        if (
            Order.objects.get(id=self.kwargs["pk"]).customer == None or self.request.user != Order.objects.get(id=self.kwargs["pk"]).customer.user
            or not self.request.user.is_authenticated 
        ):
            raise PermissionDenied
        context = super().get_context_data(**kwargs)
        context["title_label"] = "Редактирование заказа"
        return context

    def form_valid(self, form):
        # Получаем объект Customer для текущего пользователя
        customer_profile, created = Customer.objects.get_or_create(
            user=self.request.user
        )
        form.instance.customer = customer_profile
        return super().form_valid(form)

templates/freelance/customers/customer_access_order.html
{% extends 'basic/base.html' %}
{% block content %}
<h2>Заказ</h2>


<div class="container">
    <div class="row-fluid">
        <div class="col-md-10 offset-md-1">
            <h1>Детали заказа: {{ order.title }}</h1>
            <p>{{ order.description }}</p>
            <p>Стоимость: {{ order.price }}</p>
            <p>Статус: {{ order.get_status_display }}</p>
            {% if accepted_executor %}
            <h2>Исполнитель заказа:</h2>
            <h5 class="text-warning">{{ accepted_executor.executor.profile.user.username }}</h5>
            {% else %}
            <h2>Выберите исполнителя:</h2>
        </div>
        <div class="row">
            <div class="col-md-10 offset-md-1">
                <form class="form form-inline" method="post" action="{% url 'freelance:customer-access-order' order.pk %}">
                    {% for request in order.requests.all %}
                    {% csrf_token %}
                    <div class="grid grid-cols-3">
                        <div class="row">
                            <div class="col-md-2 text-center">
                            <input class="form-check-input" type="radio" name="executor"
                                value="{{ request.executor.pk }}" />
                            </div>
                            <div class="col-md-8 text-left">
                                <h5 class="text-secondary mb-0 d-inline">{{ request.executor.profile.user.username }}</h5>
                            </div>
                            <div class="col-md-2 text-center">
                                <a class="btn btn-primary btn-sm btn-block" href="{% url 'freelance:executor-detail' request.executor.pk %}">
                                    Профиль
                                </a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <input type="hidden" name="order" value="{{ order.pk }}">
                    <br>
                    <button class="btn btn-success" type="submit">Выбрать исполнителя</button>
                </form>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

<h5 class="text-warning">{{ accepted_executor.executor.profile.user.username }}</h5>
<a class="btn btn-primary btn-sm" href="{% url 'ratings:rating_update' order.pk %}"> Рейтинг </a>

templates/freelance/customers/customer_access_orders.html
{% extends 'basic/base.html' %}
{% block content %}
    <h2>Список Заказчиков</h2>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Заказ</th>
                <th scope="col">Описание</th>
                <th scope="col">Стоимость</th>
                <th scope="col">Статус</th>
                <th scope="col">Испонители</th>
                <th scope="col">Действия</th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
            <tr>
                <td>{{ order.order.pk }}</td>
                <td>
                    <a href="{% url 'freelance:customer-access-order' order.pk %}">{{ order.title }}</a>
                </td>
                <td>{{ order.order.description }}</td>
                <td>{{ order.order.price }}</td>
                <td>{{ order.order.get_status_display }}</td>
                <td>
                    {% for executor in order.executors.all %}
                    {{ executor }}
                    {% endfor %}
                </td>
                <td>
                    <a class="btn btn-primary" href="{% url 'freelance:order-detail' order.pk %}">Посмотреть</a>
                </td>
            </tr>

            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/freelance/customers/customer_list.html
{% extends 'basic/base.html' %}
{% block content %}
<h2>Список Заказчиков</h2>
<ul>
    {% for customer in customers %}
    <li><a href="{% url 'customer-detail' customer.pk %}">{{ customer.user.username }}</a></li>
    {% endfor %}
</ul>
{% endblock %}